-- Govt datasets seed (indicative, verify live)

create table if not exists jan_aushadhi(generic text, pack text, branded_mrp int, ja_price int);
create table if not exists pmjay_packages(name text, code text, indicative_price int, note text);
create table if not exists helplines(name text, number text, when_hi text, when_bn text, when_mr text);

insert into jan_aushadhi values('paracetamol','650mg x 15 tabs',35,12);
insert into jan_aushadhi values('paracetamol','500mg x 15 tabs',28,10);
insert into jan_aushadhi values('ibuprofen','400mg x 15 tabs',32,11);
insert into jan_aushadhi values('diclofenac','50mg x 10 tabs',25,8);
insert into jan_aushadhi values('aspirin','75mg x 14 tabs',18,6);
insert into jan_aushadhi values('mefenamic-acid','500mg x 10 tabs',40,14);
insert into jan_aushadhi values('azithromycin','500mg x 3 tabs',65,19);
insert into jan_aushadhi values('amoxicillin','500mg x 10 caps',75,28);
insert into jan_aushadhi values('amoxiclav','625mg x 10 tabs',190,65);
insert into jan_aushadhi values('cefixime','200mg x 10 tabs',110,42);
insert into jan_aushadhi values('ciprofloxacin','500mg x 10 tabs',70,25);
insert into jan_aushadhi values('doxycycline','100mg x 10 caps',60,22);
insert into jan_aushadhi values('metronidazole','400mg x 15 tabs',35,13);
insert into jan_aushadhi values('albendazole','400mg x 1 tab',18,7);
insert into jan_aushadhi values('metformin','500mg x 15 tabs',45,14);
insert into jan_aushadhi values('glimepiride','1mg x 15 tabs',60,16);
insert into jan_aushadhi values('sitagliptin','100mg x 15 tabs',280,90);
insert into jan_aushadhi values('losartan','50mg x 15 tabs',70,18);
insert into jan_aushadhi values('telmisartan','40mg x 15 tabs',95,22);
insert into jan_aushadhi values('amlodipine','5mg x 15 tabs',40,10);
insert into jan_aushadhi values('atenolol','50mg x 14 tabs',38,11);
insert into jan_aushadhi values('hydrochlorothiazide','12.5mg x 15 tabs',30,9);
insert into jan_aushadhi values('enalapril','5mg x 15 tabs',42,12);
insert into jan_aushadhi values('atorvastatin','10mg x 15 tabs',90,20);
insert into jan_aushadhi values('rosuvastatin','10mg x 15 tabs',120,24);
insert into jan_aushadhi values('omeprazole','20mg x 15 caps',55,14);
insert into jan_aushadhi values('pantoprazole','40mg x 15 tabs',85,18);
insert into jan_aushadhi values('antacid','170ml syrup',95,35);
insert into jan_aushadhi values('ondansetron','4mg x 10 tabs',60,16);
insert into jan_aushadhi values('ors','21.8g sachet',22,8);
insert into jan_aushadhi values('cetirizine','10mg x 15 tabs',45,10);
insert into jan_aushadhi values('levocetirizine','5mg x 15 tabs',65,14);
insert into jan_aushadhi values('montelukast','10mg x 15 tabs',140,38);
insert into jan_aushadhi values('levothyroxine','50mcg x 100 tabs',110,32);
insert into jan_aushadhi values('iron-folic','100mg x 15 tabs',35,10);
insert into jan_aushadhi values('vitamin-d3','60k IU x 4 caps',110,30);
insert into jan_aushadhi values('vitamin-b12','1500mcg x 15 tabs',75,22);
insert into jan_aushadhi values('calcium','500mg x 15 tabs',85,25);
insert into jan_aushadhi values('cough-syrup','100ml',95,38);
insert into jan_aushadhi values('multivitamin','15 caps',90,28);

insert into pmjay_packages values('Cataract surgery (Motiyabind)','PM-JAY/EYE',6500,'Lens sahit, empanelled eye hospital');
insert into pmjay_packages values('Normal delivery','PM-JAY/OBG',9000,'Maa + navjaat cover');
insert into pmjay_packages values('C-Section delivery','PM-JAY/OBG',15000,'Complication sahit');
insert into pmjay_packages values('Knee replacement (single)','PM-JAY/ORTHO',80000,'Implant sahit cap ke andar');
insert into pmjay_packages values('Hip replacement','PM-JAY/ORTHO',90000,'Implant sahit');
insert into pmjay_packages values('CABG heart bypass','PM-JAY/CARD',150000,'Top cardiac hospitals');
insert into pmjay_packages values('Angioplasty + 1 stent','PM-JAY/CARD',80000,'Drug-eluting stent');
insert into pmjay_packages values('Hernia repair','PM-JAY/SURG',20000,'Mesh sahit');
insert into pmjay_packages values('Appendix operation','PM-JAY/SURG',18000,'Laparoscopic bhi');
insert into pmjay_packages values('Gallbladder removal','PM-JAY/SURG',22000,'Laparoscopic');
insert into pmjay_packages values('Dialysis (per session)','PM-JAY/NEPH',2000,'Regular package');
insert into pmjay_packages values('Cataract both eyes','PM-JAY/EYE',13000,'Alag-alag date');
insert into pmjay_packages values('Fracture fixation (rod/plate)','PM-JAY/ORTHO',35000,'Implant sahit');
insert into pmjay_packages values('Pneumonia admission (child)','PM-JAY/PED',12000,'ICU sahit cap');
insert into pmjay_packages values('Dengue admission','PM-JAY/MED',10000,'Platelet/ICU cap ke andar');
insert into pmjay_packages values('TB package (drug-sensitive)','PM-JAY/TB',0,'NIKSHAY + DOTS se muft, PM-JAY admission cover');
insert into pmjay_packages values('Cancer chemo (per cycle)','PM-JAY/ONC',30000,'Day-care packages');
insert into pmjay_packages values('MRI brain','PM-JAY/RAD',5000,'Package ke andar jab admit');
insert into pmjay_packages values('CT scan','PM-JAY/RAD',3000,'Admit case me cover');

insert into helplines values('Ambulance (all states)','108','Emergency — accident, delivery, dil ka daura','Emergency — durghotona, delivery','Emergency — apghat, delivery');
insert into helplines values('Emergency (single)','112','Police + ambulance + fire, ek number','Police + ambulance, ek number','Police + ambulance, ek number');
insert into helplines values('Health helpline','104','Doctor salah, dawai jankari, shikayat','Doctor poramorsho','Doctor salla');
insert into helplines values('Ayushman Bharat','14555','PM-JAY patrata, card, hospital','PM-JAY card, hospital','PM-JAY patrata, card');
insert into helplines values('Jan Aushadhi','1800-180-8080','Sasti dawai, Kendra address','Sosta osudh, Kendra','Swast aushadh, Kendra');
insert into helplines values('Child helpline','1098','Bacchon ki suraksha, emergency','Shishu surakkha','Mulanche sanrakshan');
insert into helplines values('Women helpline','181','Mahila suraksha, salah','Mohila surakkha','Mahila suraksha');
insert into helplines values('Blood requirement','104','Khoon ki zaroorat par 104 dabao','Rokto dorkar e 104','Raktasathi 104');
