-- Suraksha Parchi seed for Neon (cool-math-10984187 / production)
-- Run: psql $NEON_DATABASE_URL -f sql/seed_medicines.sql

create table if not exists drug_master(
  name text primary key, brands text[] not null default '{}',
  mg text[] not null default '{}', disease_en text, icd11 text,
  hindi text, bengali text, marathi text,
  dz_hi text, dz_bn text, dz_mr text,
  red_flag boolean default false, notes text);

create table if not exists interaction_rules(
  id serial primary key, generics text[] not null, level text not null,
  hi text, bn text, mr text);

create table if not exists sehat_file(
  id uuid default gen_random_uuid() primary key,
  user_phone text, scan_type text, raw_text text,
  parsed_json jsonb, disease_guess text, lang text,
  created_at timestamptz default now());

insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('paracetamol',ARRAY['dolo','crocin','calpol','febrex'],ARRAY['500mg','650mg'],'Fever / Pain','MG48','Bukhar/dard ke liye. Khane ke baad 1 goli, din me max 3-4g. Do Paracetamol brand ek saath mat lo.','Jor/byathar jonno. Khabar pore 1 ta, dine max 3-4g. Duto brand eksathe neben na.','Taap/dukhisathi. Jevnanantar 1 goli, divsat max 3-4g. Don brand ekatra naka.','Bukhar / Dard','Jor / Byatha','Taap / Dukh',false,'Duplicate-brand overdose trap') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('ibuprofen',ARRAY['brufen','combiflam-i'],ARRAY['200mg','400mg'],'Pain / Fever / Swelling','MG48','Dard/sujan ke liye. Khane ke baad hi lo, khali pet nahi. BP/sugar dawai wale doctor se poochhein.','Byatha/fola r jonno. Khabar pore neben, khali pete noy.','Dukhi/sujisathi. Jevnanantarach ghya, rikamya poti naka.','Dard / Bukhar / Sujan','Byatha / Jor / Fola','Dukhi / Taap / Suj',false,'NSAID: ulcer, kidney, BP interaction') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('diclofenac',ARRAY['voveran','dynapar'],ARRAY['50mg'],'Joint/Muscle pain','ME82','Jod/kamar dard ke liye. Khane ke baad, lamba course doctor se.','Gire byathar jonno. Khabar pore.','Sandhedukhisathi. Jevnanantar.','Jod / Maanspeshi dard','Gire / mangser byatha','Sandhe / snayu dukhi',false,'NSAID ulcer risk') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('aspirin',ARRAY['ecosprin','loprin'],ARRAY['75mg','150mg'],'Heart protection (blood thinner)','BA00','Dil ke liye khoon patla karne wali. Roz 1, doctor ke bina band mat karo.','Heart er jonno. Doctor na bolle bondho noy.','Hrudayasathi. Doctor shivay band naka.','Dil ki suraksha','Heart surakkha','Hruday suraksha',true,'Bleeding risk; never stop abruptly') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('mefenamic-acid',ARRAY['meftal'],ARRAY['500mg'],'Period pain / Pain','GA34','Mahwari dard ke liye. Khane ke baad, 2-3 din se zyada to doctor.','Period byathar jonno. Khabar pore.','Masik palichya dukhisathi. Jevnanantar.','Mahwari dard','Period byatha','Masik pali dukhi',false,'Short course only') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('azithromycin',ARRAY['azee','azithral'],ARRAY['250mg','500mg'],'Bacterial infection (Typhoid/Chest)','1A00','Infection maarne ke liye. Roz 1 goli 3-5 din, course pura karo, beech me band mat karo.','Infection marar jonno. Roz 1 ta 3-5 din, course sesh koro.','Sansarg nasht karasathi. Roz 1 goli 3-5 divas, course purna kara.','Bacterial infection','Bacterial infection','Jivanu sansarg',false,'AMR: incomplete course danger') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('amoxicillin',ARRAY['novamox','wymox'],ARRAY['250mg','500mg'],'Bacterial throat/chest infection','CA00','Gale/chhati infection ke liye. 5 din course pura. Daane/khujli ho to turant doctor.','Gola/buker infection. 5 din course. Rash hole doctor.','Ghasa sansarg. 5 divas course. Purad aalyas doctor.','Gale/chhati infection','Gola/buker infection','Ghasa/chhati sansarg',false,'Penicillin allergy watch') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('amoxiclav',ARRAY['augmentin','megasafe'],ARRAY['625mg'],'Strong bacterial infection','1A00','Tez infection ke liye. Khane ke saath, course pura. Dast ho sakta hai.','Joralo infection. Khabar sathe, course sesh.','Tivra sansarg. Jevanasobat, course purna.','Tez infection','Joralo infection','Tivra sansarg',false,'Take with food') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('cefixime',ARRAY['taxim-o','zifi'],ARRAY['200mg'],'Typhoid / Urine infection','1A00','Typhoid/peshab infection ke liye. Roz 1-2, 7 din course pura.','Typhoid/prosrab infection. 7 din course.','Vishamjwar/mutra sansarg. 7 divas course.','Typhoid / peshab infection','Typhoid / prosrab infection','Vishamjwar / mutra sansarg',false,'Complete full course') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('ciprofloxacin',ARRAY['ciplox','cifran'],ARRAY['250mg','500mg'],'Urine / Stomach bacterial infection','1A00','Peshab/pet infection ke liye. Doodh/iron ke saath mat lo, 2 ghante gap.','Prosrab/pet infection. Dudh/iron sathe noy.','Mutra/pot sansarg. Dudh/loh sobat naka.','Peshab/pet infection','Prosrab/pet infection','Mutra/pot sansarg',false,'Gap with milk, antacids') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('doxycycline',ARRAY['doxy'],ARRAY['100mg'],'Bacterial infection / Acne','1A00','Infection ke liye. Paani ke saath khade hokar lo, dhoop se bacho.','Infection er jonno. Jol diye neben.','Sansargasathi. Panyasobat ghya.','Infection / muhase','Infection / bron','Sansarg / mhurum',false,'Sun sensitivity; no milk') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('metronidazole',ARRAY['flagyl','metrogyl'],ARRAY['200mg','400mg'],'Stomach infection / Diarrhea','1A00','Pet ke infection/dast ke liye. Dawai ke saath sharab BILKUL nahi.','Pet infection/dast. Osudh cholakalin mod noy.','Pot sansarg. Aushadhadarmyan daru ajibat naka.','Pet infection / dast','Pet infection / dast','Pot sansarg / julaab',false,'No alcohol — severe reaction') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('albendazole',ARRAY['zentel','albomar'],ARRAY['400mg'],'Worms (Kide)','1F90','Pet ke kide ke liye. 1 goli, 6 mahine baad repeat. Poora parivar le.','Krimir jonno. 1 ta, 6 mash pore abar.','Jantasathi. 1 goli, 6 mahinyani parat.','Pet ke kide','Kirmi','Jant',false,'Family deworming') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('metformin',ARRAY['glycomet','glynase-m'],ARRAY['500mg','850mg'],'Type-2 Diabetes (Sugar)','5A11','Sugar control ke liye. Khane ke saath, meetha kam, roz 30 min walk.','Sugar niyontron er jonno. Khabar sathe.','Sakhar niyantranasathi. Jevanasobat, god kami.','Sugar','Sugar','Sakhar',false,'HbA1c>8 = uncontrolled, refer') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('glimepiride',ARRAY['amaryl','glynase'],ARRAY['1mg','2mg'],'Type-2 Diabetes','5A11','Sugar ki dawai, nashte se pehle. Pasina/kampan = low sugar, turant meetha lo.','Sugar er osudh, jolkhabar age. Gham/kanpuni = low sugar.','Sakharechi goli, nashtyaadhi. Gham/tharthar = low sugar.','Sugar','Sugar','Sakhar',false,'Hypoglycemia risk') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('sitagliptin',ARRAY['januvia','istavel'],ARRAY['100mg'],'Type-2 Diabetes','5A11','Sugar ke liye. Roz 1, khana khao ya na khao.','Sugar er jonno. Roz 1 ta.','Sakharsathi. Roz 1.','Sugar','Sugar','Sakhar',false,'Pancreatitis pain = doctor') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('insulin-glargine',ARRAY['lantus','basalog'],ARRAY['100IU/ml'],'Diabetes (Insulin)','5A11','Sugar ka injection, roz same time. Dose khud mat badlo, fridge me rakho.','Sugar er injection. Nije dose bodlaben na.','Sakharache injection. Dose swataha badlu naka.','Sugar (insulin)','Sugar (insulin)','Sakhar (insulin)',true,'Dose error = emergency') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('losartan',ARRAY['losar'],ARRAY['25mg','50mg'],'High BP','BA00','High BP ke liye. Roz subah 1, namak kam. Chakkar aaye to baith jao.','High BP er jonno. Roz sokale 1, lobon kom.','High BP sathi. Roz sakali 1, meeth kami.','High BP','High BP','High BP',false,'BP>180/110 = emergency') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('telmisartan',ARRAY['telma','micardis'],ARRAY['20mg','40mg'],'High BP','BA00','High BP ke liye. Roz 1, pregnant mahila NA le.','High BP er jonno. Gorvoboti neben na.','High BP sathi. Garbhavati ne gheu naye.','High BP','High BP','High BP',true,'Unsafe in pregnancy') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('amlodipine',ARRAY['amlopress','stamlo'],ARRAY['5mg','10mg'],'High BP','BA00','BP ke liye. Pair me sujan ho sakti hai, to doctor ko batao.','BP er jonno. Pa fola hote pare.','BP sathi. Payala suj aalyas sanga.','High BP','High BP','High BP',false,'Ankle swelling common') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('atenolol',ARRAY['aten'],ARRAY['25mg','50mg'],'High BP / Heart rate','BA00','BP/dil ki dhadkan ke liye. Achanak band mat karo.','BP er jonno. Hothat bondho noy.','BP sathi. Achanak band naka.','High BP','High BP','High BP',true,'Never stop abruptly') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('hydrochlorothiazide',ARRAY['hydrazide','telma-h'],ARRAY['12.5mg','25mg'],'High BP (water pill)','BA00','Peshab badhane wali BP dawai. Subah lo, raat ko nahi.','Prosrab barano BP osudh. Sokale neben.','Lagvi vadhavnari BP goli. Sakali ghya.','High BP (peshab wali)','High BP','High BP',false,'Take in morning') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('enalapril',ARRAY['enam'],ARRAY['2.5mg','5mg'],'High BP / Heart','BA00','BP/dil ke liye. Sukhi khansi ho to doctor ko batao.','BP er jonno. Shukno kashi hole doctor.','BP sathi. Korada khokla aalyas sanga.','High BP / Dil','High BP / Heart','High BP / Hruday',false,'Dry cough common') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('atorvastatin',ARRAY['lipitor','storvas'],ARRAY['10mg','20mg'],'High Cholesterol','5C80','Cholesterol ke liye. Raat ko 1, tel-masala kam. Maanspeshiyon me dard rahe to doctor.','Cholesterol er jonno. Raate 1.','Cholesterolsathi. Ratri 1.','Cholesterol','Cholesterol','Cholesterol',false,'Muscle pain watch') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('rosuvastatin',ARRAY['roseday','crestor'],ARRAY['10mg'],'High Cholesterol','5C80','Cholesterol ke liye. Raat ko 1.','Cholesterol er jonno. Raate 1.','Cholesterolsathi. Ratri 1.','Cholesterol','Cholesterol','Cholesterol',false,'Same as atorva') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('omeprazole',ARRAY['omez'],ARRAY['20mg'],'Acidity / Gastric','DA00','Acidity ke liye. Subah khali pet 1, 2-4 hafte.','Acidity er jonno. Sokale khali pete.','Aamlatpittasathi. Sakali anashapoti.','Acidity','Acidity','Aamlapitta',false,'Black stool = emergency') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('pantoprazole',ARRAY['pan'],ARRAY['40mg'],'Acidity / Gastric','DA00','Acidity ke liye. Subah khali pet.','Acidity er jonno. Sokale khali pete.','Aamlatpittasathi. Sakali anashapoti.','Acidity','Acidity','Aamlapitta',false,'Same class as omeprazole') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('antacid',ARRAY['digene','gelusil','eno'],ARRAY['syp/sachet'],'Acidity / Gas','DA00','Gas/acidity me turant aaram. Khane ke baad 2 chammach.','Gas/acidity te aram. Khabar pore.','Gas/aamlapittat aaram. Jevnanantar.','Acidity / Gas','Acidity / Gas','Aamlapitta / Gas',false,'Other dawai se 2hr gap') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('ondansetron',ARRAY['emset','vomikind'],ARRAY['4mg'],'Vomiting (Ulti)','MD90','Ulti rokne ke liye. Jeebh par ghulne wali, paani nahi chahiye.','Bomi bondher jonno.','Ulti thambvanyasathi.','Ulti','Bomi','Ulti',false,'If blood vomit = hospital') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('loperamide',ARRAY['eldoper'],ARRAY['2mg'],'Diarrhea (Dast)','1A00','Dast rokne ke liye. Saath me ORS zaroor piyo. Khooni dast me NA lo.','Dast bondher jonno. Sathe ORS. Rokto dast e neben na.','Julaab thambvanyasathi. Sobat ORS. Raktajulaab asalyas naka.','Dast','Dast','Julaab',true,'No use in bloody diarrhea') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('ors',ARRAY['electral','ors-l'],ARRAY['sachet'],'Dehydration','1A00','Dast/ulti me paani ki kami. Uble paani me ghol ke thoda-thoda piyo.','Dast/bomi te jol ghatti. Futano jole gule khan.','Panyachi kamtarta. Ukalalelya panyat gholun pya.','Paani ki kami','Jol ghatti','Panyachi kamtarta',false,'No urine 6hr = hospital') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('cetirizine',ARRAY['cetzine','alerid'],ARRAY['10mg'],'Allergy / Cold / Itch','CA08','Chheenk/khujli ke liye. Raat ko 1, neend aa sakti hai, gaadi mat chalao.','Hanchi/chulkani. Raate 1, ghum aste pare.','Shink/khaj. Ratri 1, zop yeu shakte.','Allergy / zukham','Allergy / sordi','Allergy / sardi',false,'Drowsy — no driving') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('levocetirizine',ARRAY['levocet','xero'],ARRAY['5mg'],'Allergy','CA08','Allergy ke liye, kam neend wali. Raat ko 1.','Allergy er jonno. Raate 1.','Allergysathi. Ratri 1.','Allergy','Allergy','Allergy',false,'Less drowsy') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('montelukast',ARRAY['montair'],ARRAY['10mg'],'Asthma / Allergy','CA23','Dama/allergy ke liye. Roz raat ko 1, attack me inhaler hi kaam karega.','Hapani/allergy. Roz raate 1.','Dama/allergy. Roz ratri 1.','Dama / allergy','Hapani / allergy','Dama / allergy',false,'Not for acute attack') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('salbutamol-inhaler',ARRAY['ast carrin','aerocort'],ARRAY['100mcg'],'Asthma attack relief','CA23','Dama attack me turant aaram. Technique seekho, hafte me 2+ baar lage to doctor.','Hapani attack e aram.','Dama zatkyat aaram.','Dama attack me aaram','Hapani attack e aram','Dama zatkyat aaram',true,'Overuse = uncontrolled asthma') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('cough-syrup',ARRAY['benadryl','grilinctus','honitus'],ARRAY['2tsp'],'Cough (Khansi)','MD12','Khansi ke liye. Raat ko 2 chammach. 2 hafte se zyada khansi = TB test.','Kashir jonno. 2 soptaho besi = TB test.','Khoklyasathi. 2 aathvadyanpeksha jast = TB chachani.','Khansi','Kashi','Khokla',false,'Chronic cough = TB check') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('levothyroxine',ARRAY['thyrox','eltroxin'],ARRAY['25mcg','50mcg','100mcg'],'Thyroid (low)','5A00','Thyroid ke liye. Subah khali pet, doodh/chai se 1hr gap. Roz same time.','Thyroid er jonno. Sokale khali pete.','Thyroidsathi. Sakali anashapoti.','Thyroid','Thyroid','Thyroid',false,'Empty stomach, same time') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('iron-folic',ARRAY['feronia','autrin'],ARRAY['100mg+500mcg'],'Anemia (Khoon ki kami)','3A00','Khoon badhane ke liye. Roz 1, chai ke saath mat lo, nimbu ke saath lo.','Rokto baranor jonno. Cha sathe noy.','Rakt vadhvanyasathi. Chaha sobat naka.','Khoon ki kami','Rokto solpota','Raktachi kamtarta',false,'Black stool normal') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('vitamin-d3',ARRAY['arachitol','uprise-d3'],ARRAY['60k IU'],'Vitamin D deficiency','5B61','Haddiyon ke liye. Hafte me 1 (doctor dose), doodh ke saath.','Harer jonno. Soptahe 1.','Hadasathi. Aathvadyatun 1.','Vitamin D ki kami','Vitamin D ghatti','Vitamin D kamtarta',false,'Weekly, not daily') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('vitamin-b12',ARRAY['neurobion','cobadex'],ARRAY['1500mcg'],'B12 deficiency / Nerves','3A00','Nas/kamzori ke liye. Roz 1, shakahariyon ke liye zaroori.','Snayu/durbolota. Roz 1.','Nasya/ashaktapana. Roz 1.','B12 / nas kamzori','B12 / snayu','B12 / nasya',false,'Key for vegetarians') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('calcium',ARRAY['shelcal','ccal'],ARRAY['500mg'],'Bones (Calcium)','5B61','Haddiyon ke liye. Khane ke saath, iron se alag time par lo.','Harer jonno. Iron theke alada somoy.','Hadasathi. Lohapasun veglya veli.','Haddi (calcium)','Har (calcium)','Hade (calcium)',false,'Separate from iron') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('zinc',ARRAY['zinconia'],ARRAY['20mg'],'Immunity / Diarrhea in kids','5B61','Bacchon ke dast me ORS ke saath 10-14 din.','Bachchader dast e ORS sathe.','Mulanchya julaabat ORS sobat.','Bacchon ki suraksha','Bachchader surakkha','Mulanche sanrakshan',false,'With ORS for kids') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('antifungal-cream',ARRAY['candid','ring-guard'],ARRAY['cream'],'Fungal infection (Daad)','1F20','Daad/khajli par. Saaf-sukhi rakho, 2-4 hafte lagao, beech me mat chhodo.','Dad/chulkani te. 2-4 soptaho lagan.','Gajkarnavar. 2-4 aathvade lava.','Daad / fungal','Dad','Gajkaran',false,'Keep dry, full course') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('chloroquine',ARRAY['lariago'],ARRAY['250mg'],'Malaria','1F40','Malaria ke liye. Test ke baad hi, course pura. Bukhar wapas aaye to turant hospital.','Malaria r jonno. Test er por, course sesh.','Hivtap sathi. Chachani nanter, course purna.','Malaria','Malaria','Hivtapa',true,'Only after positive test') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('tb-dots',ARRAY['akurit'],ARRAY['combo'],'TB (6-month course)','1B10','TB ka 6 mahine course. 1 din bhi miss mat karo, DOTS center se muft milti hai.','TB r 6 masher course. Miss noy, DOTS theke free.','Kshayarogacha 6 mahinyancha course. Chukvu naka, DOTS madhun mofat.','TB','TB','Kshayrog',true,'Missed dose = drug-resistant TB') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('prednisolone',ARRAY['wysolone'],ARRAY['5mg','10mg'],'Severe allergy/asthma (steroid)','CA23','Steroid — doctor dose se kam-zyada mat karo, achanak band mat karo.','Steroid — nije kom-besi noy.','Steroid — swataha badal naka.','Steroid dawai','Steroid osudh','Steroid aushadh',true,'Taper only, sugar rises') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('multivitamin',ARRAY['becosules','supradyn'],ARRAY['daily'],'Weakness','MG48','Kamzori ke liye. Roz 1 khane ke baad. Khana hi asli dawai hai.','Durbolotar jonno. Roz 1.','Ashaktapanasathi. Roz 1.','Kamzori','Durbolota','Ashaktapana',false,'Food first') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('eye-drop',ARRAY['refresh-tears'],ARRAY['drops'],'Dry eyes','9A00','Aankhon ki jalan/sukhapn ke liye. Din me 2-3 baar 1 boond.','Chokh jolay. Dine 2-3 bar.','Dolyanchi jaljal. Divsatun 2-3 vela.','Aankh sukhaapan','Chokh shukano','Dolhe kordepana',false,'No sharing bottles') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;
insert into drug_master(name,brands,mg,disease_en,icd11,hindi,bengali,marathi,dz_hi,dz_bn,dz_mr,red_flag,notes) values('pain-gel',ARRAY['volini','moov'],ARRAY['gel'],'Muscle pain (lep)','ME82','Dard par lagane wala gel. Din me 2-3 baar, aankh me na lage.','Byathay laganor gel.','Dukhivar lavayche gel.','Maanspeshi dard (lep)','Mangser byatha (lep)','Snayu dukhi (lep)',false,'External only') on conflict(name) do update set brands=excluded.brands,mg=excluded.mg,disease_en=excluded.disease_en,icd11=excluded.icd11,hindi=excluded.hindi,bengali=excluded.bengali,marathi=excluded.marathi,dz_hi=excluded.dz_hi,dz_bn=excluded.dz_bn,dz_mr=excluded.dz_mr,red_flag=excluded.red_flag,notes=excluded.notes;

insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['paracetamol','paracetamol'],'danger','Dolo + Crocin dono Paracetamol hain — overdose se liver kharab. Ek lo, doctor se poochho.','Dolo + Crocin dutoi Paracetamol — overdose e liver kharap.','Dolo + Crocin donhi Paracetamol — overdose ne liver kharab. Ekach ghya.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['ibuprofen','aspirin'],'danger','Brufen + Ecosprin saath me pet me khoon ka khatra. Doctor ke bina mat lo.','Brufen + Ecosprin eksathe pet e rokto jhorte pare.','Brufen + Ecosprin ekatra potat raktasravacha dhoka.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['ibuprofen','losartan'],'warn','Dard ki dawai BP dawai ka asar kam karti hai + kidney load. 3 din se zyada to doctor.','Byathar osudh BP osudher kaj komay.','Dukhichi goli BP golicha parinam kami karte.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['ibuprofen','telmisartan'],'warn','Dard ki dawai BP dawai ka asar kam karti hai. Doctor ko batao.','Byathar osudh BP osudher kaj komay.','Dukhichi goli BP golicha parinam kami karte.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['metformin','metronidazole'],'warn','Sugar + infection dawai saath me — sharab bilkul nahi, sugar check karo.','Sugar + infection osudh — mod noy.','Sakhar + sansarg goli — daru naka.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['ciprofloxacin','antacid'],'warn','Cifran antacid/doodh ke saath kaam nahi karegi. 2 ghante ka gap rakho.','Cifran antacid/dudh sathe kaj korbe na. 2 ghonta gap.','Cifran antacid/dudhasobat kam karnar nahi. 2 tas gap theva.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['ciprofloxacin','iron-folic'],'warn','Cifran iron ke saath mat lo — 2 ghante gap.','Cifran iron sathe noy — 2 ghonta gap.','Cifran lohasobat naka — 2 tas gap.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['levothyroxine','iron-folic'],'warn','Thyroid + iron ek saath mat lo — 4 ghante gap, thyroid subah khali pet.','Thyroid + iron eksathe noy — 4 ghonta gap.','Thyroid + loh ekatra naka — 4 tas gap.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['levothyroxine','calcium'],'warn','Thyroid + calcium ek saath mat lo — 4 ghante gap.','Thyroid + calcium eksathe noy.','Thyroid + calcium ekatra naka.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['atenolol','salbutamol-inhaler'],'warn','Ye BP dawai dame ke inhaler ka asar kam kar sakti hai. Doctor ko batao.','Ei BP osudh inhaler er kaj komate pare.','Hi BP goli inhalercha parinam kami karu shakte.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['prednisolone','metformin'],'warn','Steroid sugar badhata hai — sugar roz check karo, doctor ko batao.','Steroid sugar baray — roj check.','Steroid sakhar vadhavte — roz tapaasa.');
insert into interaction_rules(generics,level,hi,bn,mr) values(ARRAY['aspirin','ibuprofen'],'danger','Do khoon-patla/dard dawai saath me — pet se khoon ka khatra.','Duto osudh eksathe — rokto jhorar bhoy.','Don golya ekatra — raktasravacha dhoka.');
